#CI - Continuous Integration
#CD - Continuous Deployment / Delivery

# Workflow name
name: Bank system CI/CD pipeline

# When should it run
on:
  push:
    branches: [ main,feature/* ] # If you push to the main branch or any feature branch
  pull_request:
    branches: [ main,feature/* ] # If you open a PR (Pull Request) to these branches

jobs:
  build:
    runs-on: ubuntu-latest # The virtual machine provided by GitHub

    steps:
      # Cloning the code from the GitHub repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setting up java 21 for the runtime environment
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          #The distribution parameter specifies the JDK distribution (adoptopenjdk,zulu,oraclejdk) to use for setting up the Java environment.
          distribution: 'adoptopenjdk'

      # Running tests and building the project using Gradle
      - name: Build with gradle
        # ./gradlew - executes the project's Gradle wrapper to ensure the correct Gradle version is used
        # clean - deletes all perviously built files to ensure a fresh build
        # build - compiles the code, runs the tests and creates the final build artifacts (JAR files)
        run: ./gradlew clean build
